version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: "on-failure"
    networks:
      - nginx_net
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - book_store
      - book_warehouse

  book_store:
    container_name: book_store
    build:
      context: .
      dockerfile: docker/book_store/Dockerfile
    restart: "on-failure"
    volumes:
      - ./book_store/:/usr/app/
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - nginx_net
      - store_net
    expose:
      - "8000"
    env_file:
      - book_store/store.env
    depends_on:
      - store_db

  store_db:
    container_name: store_db
    image: postgres:latest
    restart: "on-failure"
    networks:
      - store_net
    volumes:
      - store_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zxcvbnm8
      POSTGRES_DB: store_postgres
      POSTGRES_USER: store_postgres

  redis:
    container_name: store_redis
    image: redis:latest
    networks:
      - store_net

  book_warehouse:
    container_name: book_warehouse
    build:
      context: .
      dockerfile: docker/book_warehouse/Dockerfile
    restart: "on-failure"
    volumes:
      - ./book_warehouse/:/usr/app/
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    networks:
      - nginx_net
      - warehouse_net
    env_file:
      - book_warehouse/warehouse.env
    expose:
      - "8001"
    depends_on:
      - warehouse_db

  warehouse_db:
    container_name: warehouse_db
    image: postgres:latest
    restart: "on-failure"
    networks:
      - warehouse_net
    volumes:
      - warehouse_postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: zxcvbnm8
      POSTGRES_DB: warehouse_postgres
      POSTGRES_USER: warehouse_postgres

volumes:
  store_postgres:
  warehouse_postgres:
  book_store:
  book_warehouse:

networks:
  nginx_net:
  store_net:
  warehouse_net: