# Generated by Django 4.1.1 on 2022-11-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('author', models.CharField(max_length=200, null=True, verbose_name='author')),
                ('code', models.IntegerField(verbose_name='code')),
                ('publisher', models.CharField(max_length=200, null=True, verbose_name='publisher')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('quantity_str', models.CharField(blank=True, max_length=50, null=True, verbose_name='str')),
                ('year', models.CharField(blank=True, max_length=50, null=True, verbose_name='year')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50, verbose_name='barcode')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_api.book')),
            ],
        ),
    ]
