# Generated by Django 4.1.1 on 2022-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='str',
            field=models.CharField(max_length=10, null=True, verbose_name='str'),
        ),
    ]
