# Generated by Django 4.1.1 on 2022-10-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='str',
            field=models.CharField(max_length=50, null=True, verbose_name='str'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=50, null=True, verbose_name='year'),
        ),
    ]
